version: '3.7'

services:
  dm_db:
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  django:
    container_name: dm_movie
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/django_movie_drf/manage.py migrate --noinput && python /usr/src/django_movie_drf/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/django_movie_drf
    ports:
      - 8000:8000
    depends_on:
      - dm_db

volumes:
  pg_data: